### PR TITLE
Fix orders controller

### LINKED ISSUE #15: Fix orders controller

### PR DESCRIPTION
**Pull request by jiahui0309**
Fixes #15

### CODE REVIEW

File: client/src/pages/admin/AdminOrders.js [hunk 1]
```diff
@@ -22,7 +22,11 @@ const AdminOrders = () => {
   const getOrders = async () => {
     try {
       const { data } = await axios.get("/api/v1/auth/all-orders");
-      setOrders(data);
+      if (data?.success) {
+        setOrders(data.orders);
+      } else {
+        console.log("Failed to fetch orders:", data.message || "Unknown error");
```
Comment (ToxOptimism) [inline client/src/pages/admin/AdminOrders.js]: Perhaps add a whitespace after the colon?

File: client/src/pages/user/Orders.js [hunk 2]
```diff
@@ -11,7 +11,11 @@ const Orders = () => {
   const getOrders = async () => {
     try {
       const { data } = await axios.get("/api/v1/auth/orders");
-      setOrders(data);
+      if (data?.success) {
+        setOrders(data.orders);
+      } else {
+        console.log("Failed to fetch orders:", data.message || "Unknown error");
```
Comment (ToxOptimism) [inline client/src/pages/user/Orders.js]: Perhaps add a whitespace after the colon?

File: controllers/authController.js [hunk 3]
```diff
@@ -157,10 +157,17 @@ export const forgotPasswordController = async (req, res) => {
 //test controller
 export const testController = (req, res) => {
   try {
-    res.send("Protected Routes");
+    return res.status(200).send({
+      success: true,
+      message: "Protected Routes",
+    });
   } catch (error) {
     console.log(error);
```
Comment (ToxOptimism) [inline controllers/authController.js]: Perhaps a error message header could be useful in better understanding logs.

**Review by ToxOptimism — APPROVED** [review]
LGTM. Just some nits that could be looked at.
